import DashboardLayout from "@/components/DashboardLayout";
import { QueryState } from "@/components/QueryState";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { Building2, FolderTree, Pencil, Plus } from "lucide-react";
import { useState } from "react";

const unitTypes = ["regional", "unidade", "departamento", "grupo"] as const;
const unitLabels: Record<(typeof unitTypes)[number], string> = { regional: "Regional", unidade: "Unidade", departamento: "Departamento", grupo: "Grupo" };
const emptyOrganization = { code: "", name: "" };
const emptyUnit = { organizationId: "", parentId: "none", type: "unidade" as (typeof unitTypes)[number], code: "", name: "" };

type EditingOrganization = { id: number; code: string; name: string };
type EditingUnit = { id: number; organizationId: number; parentId: string; type: (typeof unitTypes)[number]; code: string; name: string };

function AccessScopesContent() {
  const scopes = trpc.access.scopes.useQuery();
  const utils = trpc.useUtils();
  const [organizationDialog, setOrganizationDialog] = useState(false);
  const [unitDialog, setUnitDialog] = useState(false);
  const [organization, setOrganization] = useState(emptyOrganization);
  const [unit, setUnit] = useState(emptyUnit);
  const [editingOrganization, setEditingOrganization] = useState<EditingOrganization | null>(null);
  const [editingUnit, setEditingUnit] = useState<EditingUnit | null>(null);
  const refreshScopes = () => utils.access.scopes.invalidate();
  const createOrganization = trpc.access.createOrganization.useMutation({ onSuccess: () => { refreshScopes(); setOrganizationDialog(false); setOrganization(emptyOrganization); } });
  const createUnit = trpc.access.createOrganizationalUnit.useMutation({ onSuccess: () => { refreshScopes(); setUnitDialog(false); setUnit(emptyUnit); } });
  const updateOrganization = trpc.access.updateOrganization.useMutation({ onSuccess: () => { refreshScopes(); setEditingOrganization(null); } });
  const updateUnit = trpc.access.updateOrganizationalUnit.useMutation({ onSuccess: () => { refreshScopes(); setEditingUnit(null); } });
  const unitsByOrganization = (organizationId: number) => (scopes.data?.units ?? []).filter(item => item.organizationId === organizationId);
  const normalizeCode = (value: string) => value.toLowerCase().replace(/[^a-z0-9_]/g, "_");

  return <div className="mx-auto max-w-[1300px] space-y-5 pb-8">
    <header className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-sky-700">Administração</p><h1 className="mt-1 text-3xl font-semibold text-slate-950">Escopos organizacionais</h1><p className="mt-1 max-w-3xl text-sm text-slate-500">Modele organizações, regionais, unidades, departamentos e grupos. Use <strong>Editar</strong> para corrigir nome, código, tipo ou vínculo hierárquico após o cadastro.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => setOrganizationDialog(true)}><Building2 className="mr-2 h-4 w-4" />Nova organização</Button><Button onClick={() => setUnitDialog(true)} disabled={!scopes.data?.organizations.length}><Plus className="mr-2 h-4 w-4" />Nova unidade</Button></div></header>
    <QueryState loading={scopes.isLoading} error={scopes.error} label="escopos organizacionais" />
    <div className="grid gap-4 lg:grid-cols-2">{(scopes.data?.organizations ?? []).map(org => <Card key={org.id} className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-slate-950">{org.name}</h2><p className="mt-1 text-xs uppercase tracking-[.12em] text-slate-500">Código {org.code}</p></div><div className="flex items-center gap-2"><Badge className="border-0 bg-emerald-50 text-emerald-800">Ativa</Badge><Button size="sm" variant="ghost" onClick={() => setEditingOrganization({ id: org.id, code: org.code, name: org.name })}><Pencil className="mr-1.5 h-3.5 w-3.5" />Editar</Button></div></div><div className="mt-5 space-y-2">{unitsByOrganization(org.id).map(item => <div key={item.id} className="flex items-center justify-between gap-3 rounded-lg border border-slate-100 bg-slate-50 px-3 py-2.5"><div className="flex min-w-0 items-center gap-2"><FolderTree className="h-4 w-4 shrink-0 text-sky-700" /><div className="min-w-0"><span className="block truncate text-sm font-medium text-slate-800">{item.name}</span><span className="block text-[11px] uppercase tracking-wide text-slate-500">{item.code}{item.parentId ? " · possui unidade-pai" : ""}</span></div></div><div className="flex shrink-0 items-center gap-1"><Badge variant="outline" className="text-[11px]">{unitLabels[item.type as (typeof unitTypes)[number]] ?? item.type}</Badge><Button size="icon" variant="ghost" className="h-8 w-8" onClick={() => setEditingUnit({ id: item.id, organizationId: item.organizationId, parentId: item.parentId ? String(item.parentId) : "none", type: item.type as (typeof unitTypes)[number], code: item.code, name: item.name })} aria-label={`Editar ${item.name}`}><Pencil className="h-3.5 w-3.5" /></Button></div></div>)}{!unitsByOrganization(org.id).length && <p className="rounded-lg border border-dashed border-slate-200 p-4 text-sm text-slate-500">Nenhuma unidade cadastrada nesta organização.</p>}</div></CardContent></Card>)}{!scopes.isLoading && !scopes.data?.organizations.length && <Card className="border-dashed border-slate-300 lg:col-span-2"><CardContent className="p-10 text-center"><Building2 className="mx-auto mb-3 h-8 w-8 text-slate-300" /><h2 className="font-semibold text-slate-800">Configure a primeira organização</h2><p className="mt-1 text-sm text-slate-500">Depois, crie unidades e atribua escopos aos papéis de cada usuário.</p><Button className="mt-4" onClick={() => setOrganizationDialog(true)}>Cadastrar organização</Button></CardContent></Card>}</div>
    <Dialog open={organizationDialog} onOpenChange={setOrganizationDialog}><DialogContent><DialogHeader><DialogTitle>Nova organização</DialogTitle><DialogDescription>O código identifica tecnicamente o escopo e deve ser único.</DialogDescription></DialogHeader><form className="grid gap-4 py-2" onSubmit={event => { event.preventDefault(); createOrganization.mutate(organization); }}><div className="grid gap-2"><Label>Código</Label><Input value={organization.code} onChange={event => setOrganization(current => ({ ...current, code: normalizeCode(event.target.value) }))} placeholder="defesa_civil" required /></div><div className="grid gap-2"><Label>Nome</Label><Input value={organization.name} onChange={event => setOrganization(current => ({ ...current, name: event.target.value }))} placeholder="Defesa Civil" required /></div>{createOrganization.error && <p role="alert" className="text-sm text-rose-700">{createOrganization.error.message}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setOrganizationDialog(false)}>Cancelar</Button><Button disabled={createOrganization.isPending}>{createOrganization.isPending ? "Salvando..." : "Salvar organização"}</Button></div></form></DialogContent></Dialog>
    <Dialog open={unitDialog} onOpenChange={setUnitDialog}><DialogContent><DialogHeader><DialogTitle>Nova unidade organizacional</DialogTitle><DialogDescription>Use o nível mais específico possível para definir o alcance dos papéis.</DialogDescription></DialogHeader><form className="grid gap-4 py-2" onSubmit={event => { event.preventDefault(); createUnit.mutate({ organizationId: Number(unit.organizationId), parentId: unit.parentId === "none" ? null : Number(unit.parentId), type: unit.type, code: unit.code, name: unit.name }); }}><OrganizationUnitFields value={unit} onChange={setUnit} organizations={scopes.data?.organizations ?? []} units={scopes.data?.units ?? []} /><ScopeFormError message={createUnit.error?.message} /><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setUnitDialog(false)}>Cancelar</Button><Button disabled={!unit.organizationId || createUnit.isPending}>{createUnit.isPending ? "Salvando..." : "Salvar unidade"}</Button></div></form></DialogContent></Dialog>
    <Dialog open={Boolean(editingOrganization)} onOpenChange={open => !open && setEditingOrganization(null)}><DialogContent><DialogHeader><DialogTitle>Editar organização</DialogTitle><DialogDescription>As alterações são auditadas. Revise o código antes de salvar, pois ele identifica o escopo em vínculos existentes.</DialogDescription></DialogHeader><form className="grid gap-4 py-2" onSubmit={event => { event.preventDefault(); if (editingOrganization) updateOrganization.mutate({ organizationId: editingOrganization.id, code: editingOrganization.code, name: editingOrganization.name }); }}><div className="grid gap-2"><Label>Código</Label><Input value={editingOrganization?.code ?? ""} onChange={event => setEditingOrganization(current => current ? { ...current, code: normalizeCode(event.target.value) } : current)} required /></div><div className="grid gap-2"><Label>Nome</Label><Input value={editingOrganization?.name ?? ""} onChange={event => setEditingOrganization(current => current ? { ...current, name: event.target.value } : current)} required /></div><ScopeFormError message={updateOrganization.error?.message} /><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setEditingOrganization(null)}>Cancelar</Button><Button disabled={updateOrganization.isPending}>{updateOrganization.isPending ? "Salvando..." : "Salvar alterações"}</Button></div></form></DialogContent></Dialog>
    <Dialog open={Boolean(editingUnit)} onOpenChange={open => !open && setEditingUnit(null)}><DialogContent><DialogHeader><DialogTitle>Editar unidade organizacional</DialogTitle><DialogDescription>Você pode alterar nome, código, tipo e unidade-pai. A aplicação impede ciclos e vínculos entre organizações distintas.</DialogDescription></DialogHeader><form className="grid gap-4 py-2" onSubmit={event => { event.preventDefault(); if (editingUnit) updateUnit.mutate({ unitId: editingUnit.id, parentId: editingUnit.parentId === "none" ? null : Number(editingUnit.parentId), type: editingUnit.type, code: editingUnit.code, name: editingUnit.name }); }}>{editingUnit && <OrganizationUnitFields value={{ ...editingUnit, organizationId: String(editingUnit.organizationId) }} onChange={next => setEditingUnit(current => current ? { ...current, parentId: next.parentId, type: next.type, code: next.code, name: next.name } : current)} organizations={scopes.data?.organizations ?? []} units={(scopes.data?.units ?? []).filter(item => item.organizationId === editingUnit.organizationId && item.id !== editingUnit.id)} organizationLocked />}<ScopeFormError message={updateUnit.error?.message} /><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setEditingUnit(null)}>Cancelar</Button><Button disabled={updateUnit.isPending}>{updateUnit.isPending ? "Salvando..." : "Salvar alterações"}</Button></div></form></DialogContent></Dialog>
  </div>;
}

type UnitFormValue = { organizationId: string; parentId: string; type: (typeof unitTypes)[number]; code: string; name: string };

function OrganizationUnitFields({ value, onChange, organizations, units, organizationLocked = false }: { value: UnitFormValue; onChange: (value: UnitFormValue) => void; organizations: Array<{ id: number; name: string }>; units: Array<{ id: number; organizationId: number; name: string }>; organizationLocked?: boolean }) {
  const normalizeCode = (code: string) => code.toLowerCase().replace(/[^a-z0-9_]/g, "_");
  return <><div className="grid gap-2"><Label>Organização</Label><Select value={value.organizationId} onValueChange={organizationId => onChange({ ...value, organizationId, parentId: "none" })} disabled={organizationLocked}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{organizations.map(org => <SelectItem key={org.id} value={String(org.id)}>{org.name}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Unidade-pai (opcional)</Label><Select value={value.parentId} onValueChange={parentId => onChange({ ...value, parentId })} disabled={!value.organizationId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Sem unidade-pai</SelectItem>{units.filter(item => item.organizationId === Number(value.organizationId)).map(item => <SelectItem key={item.id} value={String(item.id)}>{item.name}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Tipo</Label><Select value={value.type} onValueChange={type => onChange({ ...value, type: type as UnitFormValue["type"] })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{unitTypes.map(type => <SelectItem key={type} value={type}>{unitLabels[type]}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2 sm:grid-cols-2"><div className="grid gap-2"><Label>Código</Label><Input value={value.code} onChange={event => onChange({ ...value, code: normalizeCode(event.target.value) })} required /></div><div className="grid gap-2"><Label>Nome</Label><Input value={value.name} onChange={event => onChange({ ...value, name: event.target.value })} required /></div></div></>;
}

function ScopeFormError({ message }: { message?: string }) { return message ? <div role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800"><p>{message}</p>{message.includes("unidade-pai") && <p className="mt-2 text-rose-900">Como corrigir: selecione uma unidade-pai da mesma organização e que não seja descendente da unidade editada.</p>}</div> : null; }

export default function AccessScopesPage() { return <DashboardLayout><AccessScopesContent /></DashboardLayout>; }
