import React, { useMemo, useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { QueryState } from "@/components/QueryState";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { BookOpenCheck, Braces, CheckCircle2, FileCode2, FileUp, FlaskConical, PlugZap, RefreshCw, ShieldCheck } from "lucide-react";
import { toast } from "sonner";

function HttpMethod({ method }: { method: string }) {
  const color = method === "GET" ? "bg-sky-100 text-sky-900" : method === "POST" ? "bg-emerald-100 text-emerald-900" : method === "DELETE" ? "bg-rose-100 text-rose-900" : "bg-violet-100 text-violet-900";
  return <Badge className={`${color} border-0 font-mono text-[10px] hover:${color}`}>{method}</Badge>;
}

function ApiDocsContent() {
  const utils = trpc.useUtils();
  const internal = trpc.integrations.openapi.internal.useQuery(undefined, { retry: false });
  const specs = trpc.integrations.openapi.specs.useQuery(undefined, { retry: false });
  const [format, setFormat] = useState<"auto" | "json" | "yaml">("auto");
  const [document, setDocument] = useState("");
  const [selectedSpecId, setSelectedSpecId] = useState<number | null>(null);
  const selected = trpc.integrations.openapi.spec.useQuery({ specId: selectedSpecId ?? 1 }, { enabled: selectedSpecId !== null, retry: false });
  const importSpec = trpc.integrations.openapi.import.useMutation({ onSuccess: async result => { await utils.integrations.openapi.specs.invalidate(); setDocument(""); setSelectedSpecId(result.specId); toast.success(`${result.operationCount} operação(ões) OpenAPI importada(s) em simulação.`); } });
  const generate = trpc.integrations.openapi.generateConnector.useMutation({ onSuccess: async result => { await Promise.all([utils.integrations.openapi.spec.invalidate(), utils.integrations.connections.list.invalidate()]); toast.success(result.created ? "Conector simulado gerado com sucesso." : "Este conector simulado já havia sido gerado."); } });
  const testSimulation = trpc.integrations.openapi.testSimulation.useMutation({ onSuccess: result => toast.success(`Teste de contrato concluído: HTTP ${result.status}. Nenhuma requisição externa foi enviada.`) });
  const internalPaths = useMemo(() => Object.entries(internal.data?.paths ?? {}), [internal.data]);

  const importDocument = () => importSpec.mutate({ document, format });
  const loadFile = async (file: File | undefined) => { if (!file) return; if (file.size > 1_000_000) { toast.error("O arquivo deve ter no máximo 1 MB."); return; } setDocument(await file.text()); setFormat(file.name.toLowerCase().endsWith(".yaml") || file.name.toLowerCase().endsWith(".yml") ? "yaml" : "json"); };

  return <div className="mx-auto max-w-7xl space-y-6 pb-8">
    <header className="flex flex-col gap-4 rounded-2xl bg-[radial-gradient(circle_at_80%_0%,rgba(14,165,233,.24),transparent_32%),linear-gradient(112deg,#082f49,#0f766e)] px-6 py-7 text-white shadow-lg shadow-slate-900/10 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><div className="flex items-center gap-2 text-xs font-medium uppercase tracking-[0.18em] text-cyan-100"><BookOpenCheck className="h-3.5 w-3.5" /> Integrações &amp; Workflows</div><h1 className="mt-3 text-3xl font-semibold tracking-tight">API Docs / OpenAPI</h1><p className="mt-2 text-sm leading-6 text-cyan-50/90">Catálogo técnico interno, importação local de especificações e geração de conectores sem tráfego para fornecedores.</p></div><div className="flex flex-wrap gap-2"><Badge className="border border-amber-200/50 bg-amber-50/15 px-3 py-1.5 text-amber-50 hover:bg-amber-50/15">SIMULAÇÃO / MOCK</Badge><Button variant="outline" onClick={() => { internal.refetch(); specs.refetch(); }} disabled={internal.isFetching || specs.isFetching} className="border-white/35 bg-white/10 text-white hover:bg-white/20 hover:text-white"><RefreshCw className={`mr-2 h-4 w-4 ${internal.isFetching || specs.isFetching ? "animate-spin" : ""}`} />Atualizar</Button></div></header>

    <Card className="border-amber-200 bg-amber-50/70 shadow-sm"><CardContent className="flex gap-3 p-4 text-sm leading-6 text-amber-950"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-amber-700" /><p><strong>Catálogo controlado.</strong> Esta página não disponibiliza REST público, não exibe segredos e o recurso de teste grava somente uma evidência interna de simulação. Nenhum conteúdo importado é buscado, resolvido ou enviado para uma URL externa.</p></CardContent></Card>

    <section className="grid gap-6 xl:grid-cols-[minmax(0,1.25fr)_minmax(340px,.75fr)]">
      <Card className="border-slate-200 shadow-sm"><CardContent className="p-0"><div className="flex flex-col gap-3 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="flex items-center gap-2 font-semibold text-slate-950"><Braces className="h-4 w-4 text-sky-700" />Catálogo interno OpenAPI 3.1</h2><p className="mt-1 text-xs text-slate-500">Contratos documentados do módulo. Os caminhos apresentados são referência e não representam endpoints REST publicados.</p></div><Badge variant="outline" className="w-fit border-slate-200 text-slate-600">{internal.data?.openapi || "OpenAPI"}</Badge></div><QueryState loading={internal.isLoading} error={internal.error} label="catálogo OpenAPI interno" />{!internal.isLoading && !internal.error && <div className="divide-y divide-slate-100">{internalPaths.map(([path, methods]) => <div key={path} className="p-5"><p className="font-mono text-sm text-slate-800">{path}</p>{Object.entries(methods).filter(([method]) => !method.startsWith("x-")).map(([method, operation]) => { const detail = operation as { summary?: string; tags?: string[]; "x-simulation-only"?: boolean }; return <div key={method} className="mt-3 flex flex-col gap-2 rounded-xl bg-slate-50 p-3 sm:flex-row sm:items-center"><HttpMethod method={method.toUpperCase()} /><div className="min-w-0 flex-1"><p className="text-sm font-medium text-slate-800">{detail.summary || "Operação documentada"}</p><p className="text-xs text-slate-500">{detail.tags?.join(" · ") || "Integrações"}</p></div><Badge className="w-fit bg-amber-100 text-[10px] text-amber-900 hover:bg-amber-100">NÃO PUBLICADO</Badge></div>; })}</div>)}{!internalPaths.length && <p className="p-8 text-center text-sm text-slate-500">Nenhum contrato interno disponível.</p>}</div>}</CardContent></Card>

      <Card className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-center gap-2"><FileUp className="h-4 w-4 text-sky-700" /><h2 className="font-semibold text-slate-950">Importar especificação</h2></div><p className="mt-1 text-xs leading-5 text-slate-500">Aceita JSON ou YAML OpenAPI 3.0/3.1 com até 1 MB. A análise é local no AXE Dispatch e dados sensíveis são mascarados.</p><div className="mt-4 grid gap-3"><Label>Formato<Select value={format} onValueChange={value => setFormat(value as typeof format)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="auto">Detectar automaticamente</SelectItem><SelectItem value="json">JSON</SelectItem><SelectItem value="yaml">YAML</SelectItem></SelectContent></Select></Label><Label className="cursor-pointer rounded-lg border border-dashed border-slate-300 bg-slate-50 px-3 py-2 text-center text-xs text-slate-600 hover:bg-slate-100"><FileCode2 className="mr-1 inline h-3.5 w-3.5" />Carregar arquivo JSON/YAML<Input className="sr-only" type="file" accept=".json,.yaml,.yml,application/json,application/yaml,text/yaml" onChange={event => loadFile(event.target.files?.[0])} /></Label><Label>Conteúdo da especificação<Textarea value={document} onChange={event => setDocument(event.target.value)} rows={10} maxLength={1_000_000} className="font-mono text-xs" placeholder={'openapi: 3.1.0\ninfo:\n  title: Minha API\n  version: v1\npaths: ...'} /></Label>{importSpec.error && <p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{importSpec.error.message}</p>}<Button onClick={importDocument} disabled={!document.trim() || importSpec.isPending}>{importSpec.isPending ? "Analisando..." : "Analisar e importar em simulação"}</Button></div></CardContent></Card>
    </section>

    <section className="grid gap-6 xl:grid-cols-[330px_minmax(0,1fr)]"><Card className="border-slate-200 shadow-sm"><CardContent className="p-0"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-950">Especificações importadas</h2><p className="mt-1 text-xs text-slate-500">O documento original permanece sanitizado e preso ao modo de simulação.</p></div><QueryState loading={specs.isLoading} error={specs.error} label="especificações importadas" />{!specs.isLoading && !specs.error && <div className="divide-y divide-slate-100">{(specs.data ?? []).map(({ spec }) => <button key={spec.id} onClick={() => setSelectedSpecId(spec.id)} className={`w-full px-5 py-4 text-left transition-colors hover:bg-sky-50 ${selectedSpecId === spec.id ? "bg-sky-50" : ""}`}><div className="flex items-center justify-between gap-2"><strong className="truncate text-sm text-slate-900">{spec.name}</strong><Badge variant="outline" className="shrink-0 text-[10px]">{spec.apiVersion}</Badge></div><p className="mt-1 text-xs text-slate-500">{spec.operationCount} operações • OpenAPI {spec.openapiVersion}</p></button>)}{!(specs.data ?? []).length && <p className="px-5 py-8 text-center text-sm text-slate-500">Nenhuma especificação foi importada.</p>}</div>}</CardContent></Card>
      <Card className="border-slate-200 shadow-sm"><CardContent className="p-0"><div className="border-b border-slate-100 px-5 py-4"><h2 className="flex items-center gap-2 font-semibold text-slate-950"><PlugZap className="h-4 w-4 text-sky-700" />Operações e conectores</h2><p className="mt-1 text-xs text-slate-500">Gere metadados de conector para o Workflow Builder ou teste exclusivamente o contrato simulado.</p></div>{selectedSpecId === null && <p className="p-10 text-center text-sm text-slate-500">Selecione uma especificação importada para visualizar suas operações.</p>}<QueryState loading={selected.isLoading} error={selected.error} label="operações OpenAPI" />{selected.data && <div className="divide-y divide-slate-100">{selected.data.operations.map(operation => <div key={operation.id} className="flex flex-col gap-4 p-5 lg:flex-row lg:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><HttpMethod method={operation.method} /><strong className="font-mono text-sm text-slate-800">{operation.path}</strong>{operation.generatedConnectionId && <Badge className="bg-emerald-100 text-[10px] text-emerald-900 hover:bg-emerald-100"><CheckCircle2 className="mr-1 h-3 w-3" />Conector gerado</Badge>}</div><p className="mt-2 text-sm text-slate-600">{operation.summary || operation.operationKey}</p><p className="mt-1 text-xs text-slate-400">{operation.tags?.join(" · ") || "Sem categoria"} • {operation.operationKey}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => testSimulation.mutate({ operationId: operation.id })} disabled={testSimulation.isPending}><FlaskConical className="mr-1.5 h-3.5 w-3.5" />Testar</Button><Button size="sm" onClick={() => generate.mutate({ operationId: operation.id })} disabled={Boolean(operation.generatedConnectionId) || generate.isPending}><PlugZap className="mr-1.5 h-3.5 w-3.5" />{operation.generatedConnectionId ? "Gerado" : "Gerar conector"}</Button></div></div>)}{!selected.data.operations.length && <p className="p-8 text-center text-sm text-slate-500">A especificação não possui operações importadas.</p>}</div>}</CardContent></Card>
    </section>
  </div>;
}

export default function ApiDocsPage() { return <DashboardLayout><ApiDocsContent /></DashboardLayout>; }
