import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, Clock3, Loader2, RefreshCw, ShieldCheck, Siren, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";

const statusLabels: Record<string,string>={open:"Aberta",in_review:"Em análise",waiting_information:"Aguardando informação",resolved:"Resolvida",no_adjustment_required:"Sem ajuste necessário"};
const anomalyLabels: Record<string,string>={missing_start:"Início ausente",missing_end:"Término ausente",late_start:"Início atrasado",early_end:"Término antecipado",overtime:"Hora extra",excessive_pause:"Pausa excessiva",schedule_divergence:"Divergência de escala",other:"Outra anomalia"};

function Metric({label,value,icon:Icon}:{label:string;value:number;icon:typeof Clock3}){return <Card className="border-slate-200"><CardContent className="flex items-center justify-between p-5"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-950">{value}</p></div><Icon className="h-5 w-5 text-sky-700" /></CardContent></Card>}

function WorkShiftOperationsContent(){
  const [teamId,setTeamId]=useState("all");const [status,setStatus]=useState("active");
  const utils=trpc.useUtils();const access=trpc.access.me.useQuery(undefined,{retry:false});const teams=trpc.teams.list.useQuery(undefined,{retry:false});
  const input=useMemo(()=>({teamId:teamId==="all"?undefined:Number(teamId),status:status==="active"?undefined:status as "open"|"in_review"|"waiting_information"|"resolved"|"no_adjustment_required"}),[teamId,status]);
  const summary=trpc.workShiftOperations.summary.useQuery({teamId:input.teamId},{retry:false,refetchInterval:30_000});
  const pendings=trpc.workShiftOperations.list.useQuery(input,{retry:false,refetchInterval:30_000});
  const claim=trpc.workShiftOperations.claim.useMutation({onSuccess:async()=>{await Promise.all([utils.workShiftOperations.list.invalidate(),utils.workShiftOperations.summary.invalidate()]);}});
  const permissions=access.data?.permissions??[];const canManage=permissions.includes("*")||permissions.includes("work_shift_operations.manage");
  const rows=(pendings.data??[]) as Array<any>;const visibleRows=status==="active"?rows.filter(row=>!["resolved","no_adjustment_required"].includes(row.status)):rows;
  async function refresh(){await Promise.all([summary.refetch(),pendings.refetch()]);}
  if(summary.isError||pendings.isError)return <Card className="border-rose-200"><CardContent className="p-6"><h1 className="font-semibold text-rose-950">Operação de jornada indisponível</h1><p className="mt-2 text-sm text-rose-800">Verifique a permissão work_shift_operations.view e selecione uma equipe dentro do escopo autorizado.</p></CardContent></Card>;
  return <div className="mx-auto max-w-7xl space-y-6 pb-8">
    <header className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-sky-700">Central Operacional</p><h1 className="mt-1 text-3xl font-semibold text-slate-950">Operação de Jornada</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Pendências de jornada, criticidade e SLA para supervisão. Nenhuma anomalia é corrigida automaticamente.</p></div><Badge variant="outline" className="w-fit"><ShieldCheck className="mr-1.5 h-3.5 w-3.5" />{canManage?"Tratamento autorizado":"Somente leitura"}</Badge></header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Abertas" value={(summary.data as any)?.open??0} icon={Clock3}/><Metric label="Em análise" value={(summary.data as any)?.inReview??0} icon={UsersRound}/><Metric label="Críticas" value={(summary.data as any)?.critical??0} icon={Siren}/><Metric label="SLA vencido" value={(summary.data as any)?.overdue??0} icon={AlertTriangle}/><Metric label="Resolvidas" value={(summary.data as any)?.resolved??0} icon={CheckCircle2}/></div>
    <Card className="border-slate-200"><CardContent className="flex flex-col gap-4 p-5 md:flex-row md:items-end"><div className="min-w-56"><p className="mb-2 text-sm font-medium">Equipe</p><Select value={teamId} onValueChange={setTeamId}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todas no meu escopo</SelectItem>{teams.data?.map((row:any)=><SelectItem key={row.team.id} value={String(row.team.id)}>{row.team.code} — {row.team.name}</SelectItem>)}</SelectContent></Select></div><div className="min-w-56"><p className="mb-2 text-sm font-medium">Situação</p><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="active">Pendências ativas</SelectItem>{Object.entries(statusLabels).map(([key,label])=><SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select></div><Button variant="outline" onClick={refresh}><RefreshCw className="mr-2 h-4 w-4"/>Atualizar</Button></CardContent></Card>
    <Card className="border-slate-200"><CardHeader><CardTitle className="text-base">Pendências operacionais</CardTitle></CardHeader><CardContent>{pendings.isLoading?<div className="flex min-h-48 items-center justify-center gap-2 text-sm text-slate-500"><Loader2 className="h-5 w-5 animate-spin"/>Carregando jornada operacional…</div>:visibleRows.length===0?<div className="py-12 text-center text-sm text-slate-500">Nenhuma pendência encontrada para os filtros selecionados.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase tracking-wide text-slate-500"><th className="p-3">Anomalia</th><th className="p-3">Usuário</th><th className="p-3">Equipe</th><th className="p-3">Severidade</th><th className="p-3">Status</th><th className="p-3">SLA</th><th className="p-3 text-right">Ação</th></tr></thead><tbody>{visibleRows.map(row=><tr key={row.id} className="border-b last:border-0"><td className="p-3 font-medium">{anomalyLabels[row.anomalyType]??row.anomalyType}</td><td className="p-3">#{row.userId}</td><td className="p-3">{row.teamId?`#${row.teamId}`:"—"}</td><td className="p-3"><Badge variant={row.severity==="critical"?"destructive":"outline"}>{row.severity}</Badge></td><td className="p-3">{statusLabels[row.status]??row.status}</td><td className="p-3">{row.slaDueAt?new Date(row.slaDueAt).toLocaleString("pt-BR"):"Sem SLA configurado"}</td><td className="p-3 text-right">{canManage&&row.status==="open"?<Button size="sm" variant="outline" disabled={claim.isPending} onClick={()=>claim.mutate({pendingId:row.id,teamId:row.teamId??undefined,expectedVersion:row.version})}>Assumir</Button>:<span className="text-xs text-slate-400">{canManage?"Em tratamento":"Leitura"}</span>}</td></tr>)}</tbody></table></div>}</CardContent></Card>
  </div>;
}
export default function WorkShiftOperations(){return <DashboardLayout><WorkShiftOperationsContent/></DashboardLayout>}
