import express, { type Request } from "express";
import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ record: vi.fn(), recordAttempt: vi.fn(), createReview: vi.fn(), isApproved: vi.fn(), distributedRateLimit: vi.fn() }));
vi.mock("./db", () => ({ recordAlrtIncomingEvent: mocks.record, recordAlrtIngressTestAttempt: mocks.recordAttempt, createExternalIncidentReviewFromEvent: mocks.createReview, isAlrtIngressAdministrativelyApproved: mocks.isApproved, consumeAlrtDistributedRateLimit: mocks.distributedRateLimit }));
import { alrtAlertEnvelopeSchema, alrtIngressJsonErrorHandler, ALRT_API_KEY_HEADER, ALRT_INGRESS_HEALTH_PATH, ALRT_INGRESS_PATH, ALRT_SIGNATURE_HEADER, ALRT_TIMESTAMP_HEADER, consumeAlrtRateLimit, createAlrtHmacSignature, isAlrtIngressEnabled, isAlrtTimestampAccepted, registerAlrtIngressRoutes, verifyAlrtApiKey, verifyAlrtHmacSignature } from "./alrtIngress";

const payload = { schemaVersion: "1.0", eventId: "evt_alrt_8e8d7ef8-7688-4db8-a4e5-aabc7cd5cb4a", eventType: "alert.received", occurredAt: "2026-08-22T00:15:00.000Z", source: { system: "despacho-alrt", environment: "homologacao" }, correlationId: "alrt-54891", idempotencyKey: "alrt:alert:54891:created:v1", data: { alert: { externalId: "54891", category: "Alerta urbano", priority: "alta", description: "Queda de árvore bloqueando parcialmente a via.", address: "Rua Exemplo, 100 — Centro", latitude: -27.0976, longitude: -48.9104, reportedAt: "2026-08-22T00:14:45.000Z" } } };
const apiKey = "chave-de-homologacao-com-mais-de-trinta-e-dois-caracteres";
const hmacSecret = "segredo-hmac-de-teste-com-mais-de-trinta-e-dois-caracteres";

describe("receptor de homologação ALRT", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mocks.distributedRateLimit.mockResolvedValue({ allowed: true, retryAfterSeconds: 0 });
  });
  it("aceita somente o envelope de alerta de homologação com campos operacionais mínimos", () => { expect(alrtAlertEnvelopeSchema.safeParse(payload).success).toBe(true); expect(alrtAlertEnvelopeSchema.safeParse({ ...payload, eventType: "incident.created" }).success).toBe(false); expect(alrtAlertEnvelopeSchema.safeParse({ ...payload, data: { alert: { ...payload.data.alert, latitude: 91 } } }).success).toBe(false); });
  it("valida timestamp recente e chave de API sem aceitar valor incorreto", () => { expect(isAlrtTimestampAccepted("2026-08-22T00:15:00.000Z", Date.parse("2026-08-22T00:18:00.000Z"))).toBe(true); expect(isAlrtTimestampAccepted("2026-08-22T00:15:00.000Z", Date.parse("2026-08-22T00:30:01.000Z"))).toBe(false); expect(verifyAlrtApiKey(apiKey, apiKey)).toBe(true); expect(verifyAlrtApiKey("chave-incorreta", apiKey)).toBe(false); });
  it("só habilita homologação com chave de API e HMAC de tamanho seguro", () => { expect(isAlrtIngressEnabled({ mode: "homologacao", apiKey: "a".repeat(32), hmacSecret: "b".repeat(32) })).toBe(true); expect(isAlrtIngressEnabled({ mode: "producao", apiKey: "a".repeat(32), hmacSecret: "b".repeat(32) })).toBe(false); expect(isAlrtIngressEnabled({ mode: "homologacao", apiKey: "a".repeat(32), hmacSecret: "curta" })).toBe(false); });
  it("limita temporariamente recepções em excesso e informa quando o parceiro pode repetir", () => { const now = Date.now(); expect(consumeAlrtRateLimit("teste-rate-limit", 1, now)).toEqual({ allowed: true, retryAfterSeconds: 0 }); expect(consumeAlrtRateLimit("teste-rate-limit", 1, now + 1)).toMatchObject({ allowed: false, retryAfterSeconds: expect.any(Number) }); });
  it("valida a assinatura HMAC com o segredo seguro de homologação", async () => {
    expect(hmacSecret.length).toBeGreaterThanOrEqual(32); const timestamp = new Date().toISOString(); const body = JSON.stringify({ ...payload, occurredAt: timestamp, data: { alert: { ...payload.data.alert, reportedAt: timestamp } } }); const signature = createAlrtHmacSignature(timestamp, body, hmacSecret); expect(verifyAlrtHmacSignature(signature, timestamp, Buffer.from(body), hmacSecret)).toBe(true); expect(verifyAlrtHmacSignature("sha256=invalida", timestamp, Buffer.from(body), hmacSecret)).toBe(false);
    mocks.record.mockResolvedValueOnce({ event: { id: 1 }, duplicate: false }); mocks.createReview.mockResolvedValueOnce({ review: null, duplicate: false }); const app = express(); app.use(express.json({ verify: (request, _response, buffer) => { (request as Request & { rawBody?: Buffer }).rawBody = Buffer.from(buffer); } })); registerAlrtIngressRoutes(app, { mode: "homologacao", apiKey, hmacSecret, isAdministrativelyApproved: async () => true }); app.use(alrtIngressJsonErrorHandler); const server = await new Promise<ReturnType<typeof app.listen>>(resolve => { const listeningServer = app.listen(0, () => resolve(listeningServer)); });
    try { const address = server.address(); if (!address || typeof address === "string") throw new Error("Servidor de teste indisponível"); const response = await fetch(`http://127.0.0.1:${address.port}${ALRT_INGRESS_PATH}`, { method: "POST", headers: { "Content-Type": "application/json", [ALRT_API_KEY_HEADER]: apiKey, [ALRT_TIMESTAMP_HEADER]: timestamp, [ALRT_SIGNATURE_HEADER]: signature }, body }); expect(response.status).toBe(202); await expect(response.json()).resolves.toMatchObject({ success: true, status: "RECEIVED", eventId: payload.eventId }); expect(mocks.recordAttempt).toHaveBeenCalledWith(expect.objectContaining({ httpStatus: 202, result: "received" })); } finally { await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve())); }
  });
  it("registra o diagnóstico sanitizado quando uma API key é rejeitada", async () => { const app = express(); app.use(express.json({ verify: (request, _response, buffer) => { (request as Request & { rawBody?: Buffer }).rawBody = Buffer.from(buffer); } })); registerAlrtIngressRoutes(app, { mode: "homologacao", apiKey, hmacSecret: "c".repeat(32), isAdministrativelyApproved: async () => true }); const server = await new Promise<ReturnType<typeof app.listen>>(resolve => { const listeningServer = app.listen(0, () => resolve(listeningServer)); }); try { const address = server.address(); if (!address || typeof address === "string") throw new Error("Servidor de teste indisponível"); const response = await fetch(`http://127.0.0.1:${address.port}${ALRT_INGRESS_PATH}`, { method: "POST", headers: { "Content-Type": "application/json", [ALRT_API_KEY_HEADER]: "chave-incorreta", [ALRT_TIMESTAMP_HEADER]: new Date().toISOString(), "X-Correlation-Id": "teste-chave-invalida" }, body: JSON.stringify(payload) }); expect(response.status).toBe(401); expect(mocks.recordAttempt).toHaveBeenLastCalledWith(expect.objectContaining({ correlationId: "teste-chave-invalida", httpStatus: 401, result: "rejected", errorCode: "INVALID_API_KEY" })); } finally { await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve())); } });
  it("preserva o identificador de correlação do cabeçalho e rejeita divergência com o envelope", async () => {
    const timestamp = new Date().toISOString(); const body = JSON.stringify({ ...payload, correlationId: "correlacao-envelope", occurredAt: timestamp, data: { alert: { ...payload.data.alert, reportedAt: timestamp } } }); const signature = createAlrtHmacSignature(timestamp, body, hmacSecret);
    const app = express(); app.use(express.json({ verify: (request, _response, buffer) => { (request as Request & { rawBody?: Buffer }).rawBody = Buffer.from(buffer); } })); registerAlrtIngressRoutes(app, { mode: "homologacao", apiKey, hmacSecret, isAdministrativelyApproved: async () => true }); app.use(alrtIngressJsonErrorHandler); const server = await new Promise<ReturnType<typeof app.listen>>(resolve => { const listeningServer = app.listen(0, () => resolve(listeningServer)); });
    try { const address = server.address(); if (!address || typeof address === "string") throw new Error("Servidor de teste indisponível"); const response = await fetch(`http://127.0.0.1:${address.port}${ALRT_INGRESS_PATH}`, { method: "POST", headers: { "Content-Type": "application/json", [ALRT_API_KEY_HEADER]: apiKey, [ALRT_TIMESTAMP_HEADER]: timestamp, [ALRT_SIGNATURE_HEADER]: signature, "X-Correlation-Id": "correlacao-header" }, body }); expect(response.status).toBe(400); await expect(response.json()).resolves.toMatchObject({ correlationId: "correlacao-header", error: { code: "CORRELATION_MISMATCH" } }); } finally { await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve())); }
  });
  it("valida a chave fornecida no endpoint leve de prontidão após aprovação administrativa", async () => { const app = express(); registerAlrtIngressRoutes(app, { mode: "homologacao", apiKey, hmacSecret: "c".repeat(32), isAdministrativelyApproved: async () => true }); const server = await new Promise<ReturnType<typeof app.listen>>(resolve => { const listeningServer = app.listen(0, () => resolve(listeningServer)); }); try { const address = server.address(); if (!address || typeof address === "string") throw new Error("Servidor de teste indisponível"); const response = await fetch(`http://127.0.0.1:${address.port}${ALRT_INGRESS_HEALTH_PATH}`, { headers: { [ALRT_API_KEY_HEADER]: apiKey } }); expect(response.status).toBe(200); await expect(response.json()).resolves.toMatchObject({ status: "ready", mode: "homologacao", hmac: "sha256" }); } finally { await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve())); } });
  it("mantém a homologação bloqueada enquanto a aprovação administrativa não for registrada", async () => { const app = express(); registerAlrtIngressRoutes(app, { mode: "homologacao", apiKey, hmacSecret: "c".repeat(32), isAdministrativelyApproved: async () => false }); const server = await new Promise<ReturnType<typeof app.listen>>(resolve => { const listeningServer = app.listen(0, () => resolve(listeningServer)); }); try { const address = server.address(); if (!address || typeof address === "string") throw new Error("Servidor de teste indisponível"); const response = await fetch(`http://127.0.0.1:${address.port}${ALRT_INGRESS_HEALTH_PATH}`, { headers: { [ALRT_API_KEY_HEADER]: apiKey } }); expect(response.status).toBe(503); await expect(response.json()).resolves.toMatchObject({ error: { code: "ALRT_APPROVAL_PENDING" } }); } finally { await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve())); } });
  it("retorna JSON estruturado para corpo inválido sem expor erro interno", async () => { const app = express(); app.use(express.json()); registerAlrtIngressRoutes(app, { mode: "homologacao", apiKey, hmacSecret: "c".repeat(32) }); app.use(alrtIngressJsonErrorHandler); const server = await new Promise<ReturnType<typeof app.listen>>(resolve => { const listeningServer = app.listen(0, () => resolve(listeningServer)); }); try { const address = server.address(); if (!address || typeof address === "string") throw new Error("Servidor de teste indisponível"); const response = await fetch(`http://127.0.0.1:${address.port}${ALRT_INGRESS_PATH}`, { method: "POST", headers: { "Content-Type": "application/json", "X-Correlation-Id": "json-invalido-01" }, body: "{invalido" }); expect(response.status).toBe(400); await expect(response.json()).resolves.toMatchObject({ success: false, correlationId: "json-invalido-01", error: { code: "INVALID_JSON" } }); } finally { await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve())); } });
  it("rejeita o corpo acima de 256 KiB antes de autenticar ou persistir", async () => { const app = express(); registerAlrtIngressRoutes(app, { mode: "homologacao", apiKey, hmacSecret: "c".repeat(32) }); app.use(alrtIngressJsonErrorHandler); const server = await new Promise<ReturnType<typeof app.listen>>(resolve => { const listeningServer = app.listen(0, () => resolve(listeningServer)); }); try { const address = server.address(); if (!address || typeof address === "string") throw new Error("Servidor de teste indisponível"); const response = await fetch(`http://127.0.0.1:${address.port}${ALRT_INGRESS_PATH}`, { method: "POST", headers: { "Content-Type": "application/json", "X-Correlation-Id": "payload-grande-01" }, body: JSON.stringify({ data: "x".repeat(257 * 1024) }) }); expect(response.status).toBe(413); await expect(response.json()).resolves.toMatchObject({ error: { code: "PAYLOAD_TOO_LARGE" } }); expect(mocks.record).not.toHaveBeenCalled(); } finally { await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve())); } });
  it("mantém o endpoint bloqueado quando o modo, a chave ou o HMAC são revogados", async () => { const app = express(); registerAlrtIngressRoutes(app, { mode: "desativado", apiKey: "", hmacSecret: "" }); const server = await new Promise<ReturnType<typeof app.listen>>(resolve => { const listeningServer = app.listen(0, () => resolve(listeningServer)); }); try { const address = server.address(); if (!address || typeof address === "string") throw new Error("Servidor de teste indisponível"); const response = await fetch(`http://127.0.0.1:${address.port}${ALRT_INGRESS_HEALTH_PATH}`); expect(response.status).toBe(503); await expect(response.json()).resolves.toMatchObject({ error: { code: "ALRT_INGRESS_DISABLED" } }); } finally { await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve())); } });
});
