import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
const migration=readFileSync(new URL("../../drizzle/0006_d008_no_code_forms.sql",import.meta.url),"utf8");
describe("D-008 persistence contract",()=>{
it("mantém exatamente as sete tabelas aprovadas",()=>{for(const table of ["form_templates","form_versions","form_bindings","form_submissions","form_submission_revisions","form_attachments","form_domain_events"])expect(migration).toContain(`CREATE TABLE \`${table}\``);expect(migration).not.toContain("CREATE TABLE `forms`");});
it("usa estados e contextos aprovados",()=>{expect(migration).toContain("enum('draft','active','disabled')");expect(migration).toContain("enum('draft','published','retired')");expect(migration).toContain("enum('in_progress','submitted','corrected')");expect(migration).toContain("`context_type` enum('incident_category','incident','field_activity')");expect(migration).toContain("form_submissions_context_idx");});
it("fixa tenant, versão, anexos e outbox",()=>{expect(migration).toContain("form_versions_form_version_unique");expect(migration).toContain("`sha256` varchar(64) NOT NULL");expect(migration).toContain("`delivery_status` enum('pending','published','failed')");expect(migration).toContain("form_domain_events_delivery_idx");});
it("mantém FKs Drizzle essenciais para governança e histórico",()=>{for(const fk of ["form_templates_organizational_unit_id_organizational_units_id_fk","form_versions_published_by_user_id_users_id_fk","form_versions_created_by_user_id_users_id_fk","form_bindings_responsible_user_id_users_id_fk","form_bindings_team_id_teams_id_fk","form_bindings_created_by_user_id_users_id_fk","form_submissions_responsible_user_id_users_id_fk","form_submissions_team_id_teams_id_fk","form_submissions_submitted_by_user_id_users_id_fk","form_submissions_created_by_user_id_users_id_fk","form_submission_revisions_tenant_id_organizations_id_fk","form_submission_revisions_actor_user_id_users_id_fk","form_attachments_tenant_id_organizations_id_fk","form_attachments_created_by_user_id_users_id_fk"])expect(migration).toContain(fk);});
});
